version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

    commands:
      - echo update npm...
      - npm update -g npm --force
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn --force
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn run build
    
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  # include all files required to run application
  # notably excluded is node_modules, as this will cause overwrite error on deploy
  files:
    - assets/**/*
    - components/**/*
    - context/**/*
    - pages/**/*
    - public/**/*
    - redux/**/*
    - build/**/*
    - jsconfig.json
    - package.json
    - appspec.yml
    - next.config.js