export const getPercentageMeta = (type, value) => {
  const total = META_FILTER.find(
    (item) => item?.trait_type === type
  )?.options?.find((item) => item.trait_value === value)?.total

  return Math.floor((Number(total) / 8888) * 100)
}

export const BATTLE_STATS = [
  "HP",
  "ATK",
  "DEF",
  // "SUM Stat",
  "Counter Rate",
  "Evasion",
  "Accuracy",
  "Critical Rate",
  "Critical Damage",
  "Multi Hit",
  "Block Rate",
  "Pierce Rate",
]

export function shuffleArray(array) {
  for (var i = array.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1))
    var temp = array[i]
    array[i] = array[j]
    array[j] = temp
  }
  return array
}

export const filterObj = (array = [], query) =>
  array?.filter((o) =>
    Object?.keys(o)?.some((k) =>
      String(o[k]).toLowerCase().includes(query.toLowerCase())
    )
  )

const META_FILTER = [
  {
    trait_type: "Faction",
    options: [
      { trait_value: "Glacia", total: "2226" },
      { trait_value: "Ignis", total: "2222" },
      { trait_value: "Tenebris", total: "2220" },
      { trait_value: "Terra", total: "2220" },
    ],
    total: "4",
  },
  {
    trait_type: "Class",
    options: [
      { trait_value: "Knight", total: "2963" },
      { trait_value: "Marksman", total: "2963" },
      { trait_value: "Wizard", total: "2962" },
    ],
    total: "3",
  },
  {
    trait_type: "Subclass",
    options: [
      { trait_value: "Archer", total: "1587" },
      { trait_value: "Squire", total: "1587" },
      { trait_value: "Mage", total: "1586" },
      { trait_value: "Fletcher", total: "1200" },
      { trait_value: "Sorcerer", total: "1200" },
      { trait_value: "Swordman", total: "1200" },
      { trait_value: "Knight", total: "160" },
      { trait_value: "Marksman", total: "160" },
      { trait_value: "Wizard", total: "160" },
      { trait_value: "Legendary Knight", total: "16" },
      { trait_value: "Legendary Marksman", total: "16" },
      { trait_value: "Legendary Wizard", total: "16" },
    ],
    total: "12",
  },
  {
    trait_type: "Gender",
    options: [
      { trait_value: "Male", total: "4445" },
      { trait_value: "Female", total: "4443" },
    ],
    total: "2",
  },
  {
    trait_type: "Background",
    options: [
      { trait_value: "Glacian IV", total: "1194" },
      { trait_value: "Ignisian IV", total: "1190" },
      { trait_value: "Tenebrisian IV", total: "1188" },
      { trait_value: "Terran IV", total: "1188" },

      { trait_value: "Glacian III", total: "900" },
      { trait_value: "Ignisian III", total: "900" },
      { trait_value: "Tenebrisian III", total: "900" },
      { trait_value: "Terran III", total: "900" },

      { trait_value: "Glacian II", total: "120" },
      { trait_value: "Ignisian II", total: "120" },
      { trait_value: "Tenebrisian II", total: "120" },
      { trait_value: "Terran II", total: "120" },

      { trait_value: "Glacian I", total: "12" },
      { trait_value: "Ignisian I", total: "12" },
      { trait_value: "Tenebrisian I", total: "12" },
      { trait_value: "Terran I", total: "12" },
    ],
    total: "16",
  },
  {
    trait_type: "Body",
    options: [
      { trait_value: "Ginger", total: "1541" },
      { trait_value: "Tan", total: "1469" },
      { trait_value: "Beige", total: "1395" },
      { trait_value: "Grey", total: "1354" },
      { trait_value: "Pale", total: "854" },
      { trait_value: "Porcelain", total: "819" },
      { trait_value: "Chestnut", total: "741" },
      { trait_value: "Pink", total: "667" },
    ],
    total: "8",
  },
  {
    trait_type: "Hair",
    options: [
      { trait_value: "Short Blond", total: "944" },
      { trait_value: "Slick Black", total: "889" },
      { trait_value: "Slick Maroon", total: "825" },
      { trait_value: "Wild Blue", total: "793" },
      { trait_value: "Wild White", total: "741" },
      { trait_value: "Short Red", total: "675" },
      { trait_value: "Pony Tail Brown", total: "574" },
      { trait_value: "Wavy Blond", total: "535" },
      { trait_value: "Bob Hair Blond", total: "476" },
      { trait_value: "Buzz Cut Orange", total: "439" },
      { trait_value: "Buzz Cut Brown", total: "406" },
      { trait_value: "Pony Tail Black", total: "403" },
      { trait_value: "Bob Hair Beige", total: "360" },
      { trait_value: "Wavy Sage", total: "292" },
      { trait_value: "Slick Blond", total: "107" },
      { trait_value: "Wild Black", total: "107" },
      { trait_value: "Short White", total: "88" },
      { trait_value: "Buzz Cut Blue", total: "60" },
      { trait_value: "Pony Tail Blond", total: "44" },
      { trait_value: "Wavy Pink", total: "43" },
      { trait_value: "Bob Hair Purple", total: "39" },
    ],
    total: "21",
  },
  {
    trait_type: "Weapon",
    options: [
      { trait_value: "Flower Bow", total: 32 },
      { trait_value: "Wolf Bow Grey", total: 191 },
      { trait_value: "Cultist Staff Black", total: 121 },
      { trait_value: "Fork Staff Purple", total: 98 },
      { trait_value: "Long Rod Blue", total: 187 },
      { trait_value: "Wooden Bow Brown", total: 158 },
      { trait_value: "Priest Staff Purple", total: 148 },
      { trait_value: "Mercenary Sword Bronze", total: 117 },
      { trait_value: "Scottsmen Bow Brown", total: 137 },
      { trait_value: "Mage Staff Cyan", total: 115 },
      { trait_value: "Mercenary Sword Silver", total: 228 },
      { trait_value: "Leafy Bow Yellow", total: 89 },
      { trait_value: "Beast Blade Red", total: 265 },
      { trait_value: "Rusty Sword Bronze", total: 236 },
      { trait_value: "Curved Bow Black", total: 92 },
      { trait_value: "Ranger Bow Brown", total: 158 },
      { trait_value: "Winter Staff Blue", total: 93 },
      { trait_value: "Wooden Staff White", total: 195 },
      { trait_value: "Ent Bow Brown", total: 172 },
      { trait_value: "Dragon Rapier Orange", total: 75 },
      { trait_value: "Barbarian Sword Silver", total: 128 },
      { trait_value: "Long Rod Black", total: 193 },
      { trait_value: "Iron Bow Gold", total: 76 },
      { trait_value: "Slime Sword Green", total: 4 },
      { trait_value: "Celtic Sword Gold", total: 17 },
      { trait_value: "Pharaoh Staff Silver", total: 84 },
      { trait_value: "Elfen Bow White", total: 101 },
      { trait_value: "Autumn Staff Orange", total: 78 },
      { trait_value: "Crab Blade Blue", total: 148 },
      { trait_value: "Rusty Sword Black", total: 109 },
      { trait_value: "Arabic Staff Silver", total: 95 },
      { trait_value: "Dwarven Sword Bronze", total: 146 },
      { trait_value: "Crab Blade Orange", total: 149 },
      { trait_value: "Celtic Sword Silver", total: 138 },
      { trait_value: "Iron Bow Silver", total: 169 },
      { trait_value: "Leafy Bow Green", total: 170 },
      { trait_value: "Wooden Bow White", total: 140 },
      { trait_value: "Bladed Bow Silver", total: 89 },
      { trait_value: "Antler Bow Brown", total: 96 },
      { trait_value: "Ranger Bow Black", total: 78 },
      { trait_value: "Shaman Staff Brown", total: 193 },
      { trait_value: "Spartan Sword Silver", total: 111 },
      { trait_value: "Crystal Wand Blue", total: 72 },
      { trait_value: "Dual Sword Silver", total: 14 },
      { trait_value: "Eagle Staff Blue", total: 76 },
      { trait_value: "Cultist Staff Red", total: 74 },
      { trait_value: "Short Bow Red", total: 130 },
      { trait_value: "Holy Sword Silver", total: 10 },
      { trait_value: "Curved Bow Brown", total: 149 },
      { trait_value: "Shaman Staff Grey", total: 75 },
      { trait_value: "Chef Blade Purple", total: 92 },
      { trait_value: "Scottsmen Bow White", total: 91 },
      { trait_value: "Fork Staff Orange", total: 167 },
      { trait_value: "Spartan Sword Gold", total: 15 },
      { trait_value: "Dwarven Sword Red", total: 79 },
      { trait_value: "Ent Bow Green", total: 64 },
      { trait_value: "Chef Blade Orange", total: 89 },
      { trait_value: "Ice Bow Blue", total: 15 },
      { trait_value: "Priest Staff Blue", total: 167 },
      { trait_value: "Pharaoh Staff Gold", total: 21 },
      { trait_value: "Phoenix Bow Green", total: 8 },
      { trait_value: "Gladiator Sword Bronze", total: 108 },
      { trait_value: "Flower Staff", total: 22 },
      { trait_value: "Wooden Staff Brown", total: 185 },
      { trait_value: "Gladiator Sword Silver", total: 219 },
      { trait_value: "Cross Staff Silver", total: 20 },
      { trait_value: "Beast Blade Blue", total: 115 },
      { trait_value: "Paper Bow", total: 24 },
      { trait_value: "Paper Wand", total: 24 },
      { trait_value: "Autumn Staff White", total: 58 },
      { trait_value: "Mage Staff Magenta", total: 58 },
      { trait_value: "Banana Sword", total: 18 },
      { trait_value: "Wolf Bow White", total: 72 },
      { trait_value: "Angel Staff Gold", total: 4 },
      { trait_value: "Winter Staff White", total: 30 },
      { trait_value: "Dragonic Sword Orange", total: 11 },
      { trait_value: "Dragon Rapier Green", total: 86 },
      { trait_value: "Short Bow Blue", total: 127 },
      { trait_value: "Cherry Sword", total: 19 },
      { trait_value: "Scarab Blade Gold", total: 4 },
      { trait_value: "Arabic Staff Gold", total: 18 },
      { trait_value: "Ice Blade Blue", total: 20 },
      { trait_value: "Bladed Bow Gold", total: 19 },
      { trait_value: "Orb Staff Yellow", total: 17 },
      { trait_value: "Banana Staff", total: 18 },
      { trait_value: "Serpent Sword Silver", total: 9 },
      { trait_value: "Griffin Sword Red", total: 15 },
      { trait_value: "Banana Bow", total: 16 },
      { trait_value: "Crystal Wand Green", total: 81 },
      { trait_value: "Griffin Sword Blue", total: 12 },
      { trait_value: "Antler Bow Black", total: 18 },
      { trait_value: "Eagle Bow Blue", total: 72 },
      { trait_value: "Vampire Staff Purple", total: 7 },
      { trait_value: "Dragonic Bow Orange", total: 17 },
      { trait_value: "Eagle Staff Gold", total: 24 },
      { trait_value: "Cherry Bow", total: 14 },
      { trait_value: "Paper Sword", total: 16 },
      { trait_value: "Falcon Bow Blue", total: 16 },
      { trait_value: "Serpent Sword Black", total: 10 },
      { trait_value: "Orb Staff Red", total: 21 },
      { trait_value: "Cross Staff Gold", total: 4 },
      { trait_value: "Dual Sword Black", total: 15 },
      { trait_value: "Vampire Staff Red", total: 8 },
      { trait_value: "Eagle Bow Gold", total: 18 },
      { trait_value: "Poseidon Staff Blue", total: 15 },
      { trait_value: "Mongol Bow Black", total: 15 },
      { trait_value: "Dragonic Bow Green", total: 9 },
      { trait_value: "Icy Staff Purple", total: 7 },
      { trait_value: "Owlette Bow Blue", total: 16 },
      { trait_value: "Ice Bow Purple", total: 9 },
      { trait_value: "Dragonic Sword Green", total: 11 },
      { trait_value: "Icy Staff Blue", total: 10 },
      { trait_value: "Flower Sword", total: 19 },
      { trait_value: "Scarab Blade Green", total: 16 },
      { trait_value: "Rapier Blue", total: 16 },
      { trait_value: "Poseidon Staff Green", total: 9 },
      { trait_value: "Holy Bow Gold", total: 5 },
      { trait_value: "Ice Blade White", total: 10 },
      { trait_value: "Holy Bow Silver", total: 7 },
      { trait_value: "Holy Sword Gold", total: 4 },
      { trait_value: "Cherry Staff", total: 16 },
      { trait_value: "Mongol Bow Blue", total: 10 },
      { trait_value: "Owlette Bow Black", total: 7 },
      { trait_value: "Phoenix Bow Red", total: 4 },
      { trait_value: "Falcon Bow Green", total: 9 },
      { trait_value: "Slime Sword Pink", total: 4 },
      { trait_value: "Rapier Gold", total: 4 },
      { trait_value: "Elfen Bow Black", total: 25 },
      { trait_value: "Luna Staff Blue", total: 7 },
      { trait_value: "Slime Staff Green", total: 4 },
      { trait_value: "Slime Bow Green", total: 6 },
      { trait_value: "Barbarian Sword Gold", total: 16 },
      { trait_value: "Luna Staff White", total: 6 },
      { trait_value: "Dragonic Staff Green", total: 8 },
      { trait_value: "Slime Bow Pink", total: 7 },
      { trait_value: "Angel Staff White", total: 6 },
      { trait_value: "Dragonic Staff Orange", total: 3 },
      { trait_value: "Slime Staff Pink", total: 4 },
    ],
    total: "138",
  },
  {
    trait_type: "Armor",
    options: [
      { trait_value: "Hunter Red", total: 84 },
      { trait_value: "Ent Green", total: 182 },
      { trait_value: "Pharaoh Silver", total: 144 },
      { trait_value: "Priest Silver", total: 144 },
      { trait_value: "Monk Robe Green", total: 136 },
      { trait_value: "Elfen Purple", total: 150 },
      { trait_value: "Scrappy Armor Bronze", total: 160 },
      { trait_value: "Scottsmen Green", total: 120 },
      { trait_value: "Enchanted Cape Blue", total: 64 },
      { trait_value: "Mercenary Black", total: 80 },
      { trait_value: "Ranger Green", total: 84 },
      { trait_value: "Spikey Green", total: 168 },
      { trait_value: "Beast Blue", total: 164 },
      { trait_value: "Winter Arm Purple", total: 162 },
      { trait_value: "Gladiator White", total: 84 },
      { trait_value: "Ranger Red", total: 156 },
      { trait_value: "Spartan Gold", total: 44 },
      { trait_value: "Autumn Orange", total: 156 },
      { trait_value: "Shaman Black", total: 108 },
      { trait_value: "Metal Arm Silver", total: 150 },
      { trait_value: "Antler Green", total: 149 },
      { trait_value: "Crab Blue", total: 138 },
      { trait_value: "Crab Orange", total: 60 },
      { trait_value: "Autumn White", total: 110 },
      { trait_value: "Shaman Brown", total: 134 },
      { trait_value: "Scarab Silver", total: 14 },
      { trait_value: "Crab Green", total: 142 },
      { trait_value: "Elfen Blue", total: 84 },
      { trait_value: "Pharaoh Red", total: 82 },
      { trait_value: "Iron Armor Silver", total: 92 },
      { trait_value: "Dwarven White", total: 52 },
      { trait_value: "Gladiator Grey", total: 181 },
      { trait_value: "Arabic Blue", total: 136 },
      { trait_value: "Mercenary Blue", total: 154 },
      { trait_value: "Enchanted Cape Green", total: 140 },
      { trait_value: "Crusader Green", total: 64 },
      { trait_value: "Dwarven Bronze", total: 82 },
      { trait_value: "Ent Orange", total: 28 },
      { trait_value: "Wolf Grey", total: 182 },
      { trait_value: "Antler Orange", total: 80 },
      { trait_value: "Spartan Silver", total: 172 },
      { trait_value: "Mage Robe Magenta", total: 144 },
      { trait_value: "Mage Robe Cyan", total: 112 },
      { trait_value: "Wolf Black", total: 98 },
      { trait_value: "Scottsmen Purple", total: 140 },
      { trait_value: "Winter Blue", total: 152 },
      { trait_value: "Cultist Purple", total: 156 },
      { trait_value: "Priest Gold", total: 18 },
      { trait_value: "Woodland Green", total: 180 },
      { trait_value: "Cultist Red", total: 62 },
      { trait_value: "Azure Blue", total: 84 },
      { trait_value: "Serpent Silver", total: 16 },
      { trait_value: "Nature Robe Blue", total: 160 },
      { trait_value: "Ent Brown", total: 112 },
      { trait_value: "Celtic White", total: 60 },
      { trait_value: "Celtic Green", total: 100 },
      { trait_value: "Leather Armor Green", total: 156 },
      { trait_value: "Drake Orange", total: 16 },
      { trait_value: "Winter Arm Red", total: 74 },
      { trait_value: "Hunter Green", total: 120 },
      { trait_value: "Crusader Purple", total: 24 },
      { trait_value: "Scrappy Armor Gold", total: 72 },
      { trait_value: "Mongol Green", total: 12 },
      { trait_value: "Celtic Black", total: 30 },
      { trait_value: "Leather Armor Blue", total: 78 },
      { trait_value: "Pharaoh Gold", total: 24 },
      { trait_value: "Spikey Red", total: 112 },
      { trait_value: "Cultist Black", total: 16 },
      { trait_value: "Metal Arm Gold", total: 60 },
      { trait_value: "Poseidon Purple", total: 4 },
      { trait_value: "Nature Robe Purple", total: 108 },
      { trait_value: "Woodland Blue", total: 86 },
      { trait_value: "Monk Robe Gold", total: 162 },
      { trait_value: "Challenger Blue", total: 56 },
      { trait_value: "Challenger Red", total: 42 },
      { trait_value: "Dwarven Red", total: 74 },
      { trait_value: "Phoenix Green", total: 16 },
      { trait_value: "Luna Robe White", total: 12 },
      { trait_value: "Priest Purple", total: 64 },
      { trait_value: "Griffin White", total: 4 },
      { trait_value: "Iron Armor Gold", total: 24 },
      { trait_value: "Wyvern Armor Lightblue", total: 14 },
      { trait_value: "Challenger Green", total: 98 },
      { trait_value: "Griffin Blue", total: 18 },
      { trait_value: "Angel Red", total: 12 },
      { trait_value: "Azure Purple", total: 42 },
      { trait_value: "Beast Red", total: 70 },
      { trait_value: "Dragonic Green", total: 16 },
      { trait_value: "Scottsmen Blue", total: 24 },
      { trait_value: "Winter Purple", total: 104 },
      { trait_value: "Enchanted Cape Orange", total: 76 },
      { trait_value: "Mongol Purple", total: 4 },
      { trait_value: "Crusader Blue", total: 62 },
      { trait_value: "Angel Gold", total: 4 },
      { trait_value: "Mongol Black", total: 16 },
      { trait_value: "Arabic White", total: 56 },
      { trait_value: "Phoenix Red", total: 12 },
      { trait_value: "Wyvern Armor Crimson", total: 12 },
      { trait_value: "Winter Dragon Green", total: 12 },
      { trait_value: "Falcon Blue", total: 16 },
      { trait_value: "Serpent Green", total: 14 },
      { trait_value: "Poseidon Blue", total: 16 },
      { trait_value: "Arabic Gold", total: 18 },
      { trait_value: "Scarab Green", total: 18 },
      { trait_value: "Griffin Red", total: 8 },
      { trait_value: "Winter Dragon Blue", total: 16 },
      { trait_value: "Luna Robe Blue", total: 16 },
      { trait_value: "Owlette Blue", total: 16 },
      { trait_value: "Vampire Purple", total: 16 },
      { trait_value: "Vampire Black", total: 4 },
      { trait_value: "Wolf Gold", total: 18 },
      { trait_value: "Drake Red", total: 12 },
      { trait_value: "Vampire Red", total: 12 },
      { trait_value: "Wyvern Armor Black", total: 4 },
      { trait_value: "Woodland Red", total: 30 },
      { trait_value: "Falcon Green", total: 12 },
      { trait_value: "Dragonic Orange", total: 10 },
      { trait_value: "Dragonic Yellow", total: 4 },
      { trait_value: "Scarab Gold", total: 4 },
      { trait_value: "Owlette Red", total: 12 },
      { trait_value: "Drake Yellow", total: 4 },
      { trait_value: "Angel White", total: 16 },
      { trait_value: "Poseidon Green", total: 12 },
      { trait_value: "Serpent Black", total: 4 },
      { trait_value: "Luna Robe Red", total: 4 },
      { trait_value: "Owlette Black", total: 4 },
      { trait_value: "Winter Dragon White", total: 4 },
      { trait_value: "Falcon Purple", total: 4 },
      { trait_value: "Phoenix Gold", total: 4 },
    ],
    total: "129",
  },
  {
    trait_type: "Head",
    options: [
      { trait_value: "Berret Blue", total: 156 },
      { trait_value: "Wolf Grey", total: 170 },
      { trait_value: "Cultist Red", total: 134 },
      { trait_value: "Priest Gold", total: 16 },
      { trait_value: "Winter Blue", total: 177 },
      { trait_value: "Cultist Purple", total: 58 },
      { trait_value: "Spartan Gold", total: 84 },
      { trait_value: "Arabic Gold", total: 16 },
      { trait_value: "Flower Hat", total: 131 },
      { trait_value: "Elfen Blue", total: 97 },
      { trait_value: "Gladiator Grey", total: 156 },
      { trait_value: "Gladiator White", total: 137 },
      { trait_value: "Beast Blue", total: 155 },
      { trait_value: "Ranger Red", total: 119 },
      { trait_value: "Paper Hat", total: 135 },
      { trait_value: "Autumn Orange", total: 170 },
      { trait_value: "Monk Hood Green", total: 180 },
      { trait_value: "Ent Brown", total: 82 },
      { trait_value: "None", total: 538 },
      { trait_value: "Crusader Green", total: 38 },
      { trait_value: "Challenger Blue", total: 87 },
      { trait_value: "Shaman Brown", total: 158 },
      { trait_value: "Serpent Silver", total: 14 },
      { trait_value: "Jester Hat", total: 101 },
      { trait_value: "Shaman Black", total: 141 },
      { trait_value: "Iron Helmet Gold", total: 33 },
      { trait_value: "Crusader Purple", total: 42 },
      { trait_value: "Arabic Blue", total: 133 },
      { trait_value: "Beast Red", total: 239 },
      { trait_value: "Priest Silver", total: 117 },
      { trait_value: "Dwarven Bronze", total: 91 },
      { trait_value: "Celtic White", total: 33 },
      { trait_value: "Iron Helmet Silver", total: 91 },
      { trait_value: "Dwarven Red", total: 84 },
      { trait_value: "Woodland Blue", total: 90 },
      { trait_value: "Antler Green", total: 162 },
      { trait_value: "Hunter Green", total: 157 },
      { trait_value: "Woodland Green", total: 162 },
      { trait_value: "Bear Beanie", total: 93 },
      { trait_value: "Berret Green", total: 112 },
      { trait_value: "Party Hat Blue", total: 63 },
      { trait_value: "Scottsmen Green", total: 97 },
      { trait_value: "Banana", total: 66 },
      { trait_value: "Crab Green", total: 102 },
      { trait_value: "Autumn White", total: 143 },
      { trait_value: "Scottsmen Blue", total: 18 },
      { trait_value: "Cat Beanie", total: 72 },
      { trait_value: "Enchanted Cape Orange", total: 62 },
      { trait_value: "Enchanted Cape Green", total: 134 },
      { trait_value: "Pharaoh Silver", total: 132 },
      { trait_value: "Wolf Gold", total: 18 },
      { trait_value: "Mercenary Blue", total: 174 },
      { trait_value: "Elfen Purple", total: 142 },
      { trait_value: "Antler Orange", total: 83 },
      { trait_value: "Party Hat Pink", total: 51 },
      { trait_value: "Pumpkin Hat", total: 24 },
      { trait_value: "Hunter Red", total: 103 },
      { trait_value: "Winter Purple", total: 140 },
      { trait_value: "Ent Green", total: 162 },
      { trait_value: "Enchanted Cape Blue", total: 58 },
      { trait_value: "Monk Hood Gold", total: 142 },
      { trait_value: "Wolf Black", total: 83 },
      { trait_value: "Spartan Silver", total: 139 },
      { trait_value: "Celtic Black", total: 50 },
      { trait_value: "Scottsmen Purple", total: 166 },
      { trait_value: "Crab Orange", total: 42 },
      { trait_value: "Mercenary Black", total: 144 },
      { trait_value: "Drake Orange", total: 12 },
      { trait_value: "Celtic Green", total: 41 },
      { trait_value: "Halo", total: 48 },
      { trait_value: "Vampire Purple", total: 14 },
      { trait_value: "Challenger Red", total: 56 },
      { trait_value: "Ranger Green", total: 137 },
      { trait_value: "Crab Blue", total: 104 },
      { trait_value: "Cherry", total: 65 },
      { trait_value: "Crusader Blue", total: 98 },
      { trait_value: "Ent Orange", total: 16 },
      { trait_value: "Drake Red", total: 10 },
      { trait_value: "Vampire Red", total: 8 },
      { trait_value: "Dragonic Green", total: 13 },
      { trait_value: "Challenger Green", total: 46 },
      { trait_value: "Dragonic Orange", total: 11 },
      { trait_value: "Wyvern Helmet Crimson", total: 10 },
      { trait_value: "Pharaoh Red", total: 60 },
      { trait_value: "Dwarven White", total: 45 },
      { trait_value: "Poseidon Purple", total: 4 },
      { trait_value: "Slime Hat Red", total: 15 },
      { trait_value: "Griffin Red", total: 8 },
      { trait_value: "Priest Purple", total: 64 },
      { trait_value: "Serpent Green", total: 12 },
      { trait_value: "Mongol Green", total: 10 },
      { trait_value: "Poseidon Green", total: 10 },
      { trait_value: "Owlette Blue", total: 12 },
      { trait_value: "Griffin Blue", total: 14 },
      { trait_value: "Luna Hat Blue", total: 14 },
      { trait_value: "Falcon Purple", total: 4 },
      { trait_value: "Winter Crown Blue", total: 14 },
      { trait_value: "Winter Crown Green", total: 10 },
      { trait_value: "Luna Hat White", total: 8 },
      { trait_value: "Angel Wing", total: 18 },
      { trait_value: "Scarab Green", total: 12 },
      { trait_value: "Scarab Silver", total: 8 },
      { trait_value: "Angel White", total: 14 },
      { trait_value: "Phoenix Gold", total: 4 },
      { trait_value: "Arabic White", total: 62 },
      { trait_value: "Owlette Red", total: 10 },
      { trait_value: "Scarab Gold", total: 4 },
      { trait_value: "Angel Red", total: 10 },
      { trait_value: "Cultist Black", total: 16 },
      { trait_value: "Wyvern Helmet Lightblue", total: 14 },
      { trait_value: "Poseidon Blue", total: 14 },
      { trait_value: "Pharaoh Gold", total: 20 },
      { trait_value: "Mongol Black", total: 13 },
      { trait_value: "Slime Hat Green", total: 15 },
      { trait_value: "Falcon Green", total: 10 },
      { trait_value: "Woodland Red", total: 20 },
      { trait_value: "Dragonic Yellow", total: 4 },
      { trait_value: "Mongol Purple", total: 4 },
      { trait_value: "Luna Hat Red", total: 4 },
      { trait_value: "Falcon Blue", total: 12 },
      { trait_value: "Griffin White", total: 4 },
      { trait_value: "Phoenix Green", total: 16 },
      { trait_value: "Phoenix Red", total: 12 },
      { trait_value: "Wyvern Helmet Black", total: 4 },
      { trait_value: "Serpent Black", total: 4 },
      { trait_value: "Winter Crown White", total: 4 },
      { trait_value: "Angel Gold", total: 4 },
      { trait_value: "Owlette Black", total: 4 },
      { trait_value: "Drake Yellow", total: 4 },
      { trait_value: "Vampire Black", total: 4 },
    ],
    total: "130",
  },
  {
    trait_type: "Original Set",
    options: [
      { trait_value: "Woodland Green", total: 1 },
      { trait_value: "Luna Red", total: 1 },
      { trait_value: "Shaman Black", total: 1 },
      { trait_value: "Wolf Black", total: 1 },
      { trait_value: "Priest Purple", total: 1 },
      { trait_value: "Falcon Blue", total: 1 },
      { trait_value: "Wyvern Crimson", total: 1 },
      { trait_value: "Ent Green", total: 1 },
      { trait_value: "Dwarven White", total: 1 },
      { trait_value: "Poseidon Green", total: 1 },
      { trait_value: "Owlette Blue", total: 1 },
      { trait_value: "Winter Blue", total: 2 },
      { trait_value: "Challenger Blue", total: 1 },
      { trait_value: "Mercenary Black", total: 1 },
      { trait_value: "Phoenix Red", total: 1 },
      { trait_value: "Enchanted Green", total: 1 },
      { trait_value: "Gladiator White", total: 1 },
      { trait_value: "Challenger Red", total: 1 },
      { trait_value: "Celtic Black", total: 1 },
      { trait_value: "Spartan Silver", total: 1 },
      { trait_value: "Pharaoh Gold", total: 1 },
      { trait_value: "Hunter Red", total: 1 },
      { trait_value: "Scottsmen Purple", total: 1 },
      { trait_value: "Ranger Green", total: 1 },
      { trait_value: "Dragonic Green", total: 1 },
      { trait_value: "Crusader Purple", total: 1 },
      { trait_value: "Crab Blue", total: 1 },
      { trait_value: "Drake Red", total: 1 },
      { trait_value: "Arabic Blue", total: 1 },
      { trait_value: "Beast Red", total: 1 },
      { trait_value: "Mongol Blue", total: 1 },
      { trait_value: "Serpent Black", total: 1 },
      { trait_value: "Iron Silver", total: 1 },
      { trait_value: "Elfen Blue", total: 1 },
      { trait_value: "Scarab Green", total: 1 },
      { trait_value: "Cultist Purple", total: 1 },
      { trait_value: "Angel Gold", total: 1 },
      { trait_value: "Antler Green", total: 1 },
      { trait_value: "Autumn Orange", total: 1 },
      { trait_value: "Griffin Red", total: 1 },
      { trait_value: "Vampire Purple", total: 1 },
    ],
    total: "41",
  },
]
//without weapon, armor, head: 48

export default META_FILTER
